In [2]:
import numpy as np

# the elements in a NumPy array should be homogeneous

In [3]:
#To create a NumPy array, you can use the function np.array()
a = np.array([10, 20, 30, 40, 50, 60])

In [4]:
a

array([10, 20, 30, 40, 50, 60])

In [5]:
#access elements
a[0]

10

In [6]:
#np.zeros()
b=np.zeros(4)
b

array([0., 0., 0., 0.])

In [8]:
#To create a NumPy array, you can use the function np.array()
b = np.array([[10, 20, 30], [40, 50, 60]])

In [11]:
b.size #number of elements

6

In [12]:
b.shape #dimensions of array

(2, 3)

In [37]:
#find the number of dimensions of the array
b.ndim

2

In [41]:
b = np.array([
    [
        [10, 20, 30]
    ], 
    [
        [40, 50,60]
    ],
    [
        [70,80,90]
    ]
])
b.ndim

3

In [42]:
b.shape

(3, 1, 3)

# create an array filled with 0’s

In [32]:
np.zeros(4)

array([0., 0., 0., 0.])

# an array filled with 1’s

In [33]:
#the default data type is floating point (np.float64)
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
#you can explicitly specify which data type you want using the dtype keyword
np.ones(3,dtype=np.int64)

array([1, 1, 1], dtype=int64)

# The function empty creates an array whose initial content is random and depends on the state of the memory. 

In [19]:
np.empty(3)

array([8.44747281e+252, 9.78766460e+199, 4.84287705e+257])

# create an array with a range of element

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# an array that contains a range of evenly spaced intervals

In [24]:
np.arange(0,12,3) # arange(first number, last number,the step size)

array([0, 3, 6, 9])

# create an array with values that are spaced linearly in a specified interval

In [31]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

# concatenate - np.concatenate((arr,....))

In [44]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])

In [46]:
np.concatenate((arr1,arr2))

array([10, 20, 30, 40, 50, 60])

In [47]:
np.concatenate((arr1,arr2),axis=0)

array([10, 20, 30, 40, 50, 60])

In [57]:
arr1=np.array([[10,20,30],[15,25,35],[16,26,36]])
arr2=np.array([[40,50,60],[45,55,65],[46,56,66]])

In [62]:
np.concatenate((arr1,arr2),axis=1)

array([[10, 20, 30, 40, 50, 60],
       [15, 25, 35, 45, 55, 65],
       [16, 26, 36, 46, 56, 66]])

In [64]:
arr1=np.array([[[10,20,30]],[[15,25,35]],[[16,26,36]]])
arr2=np.array([[[40,50,60]],[[45,55,65]],[[46,56,66]]])

In [65]:
np.concatenate((arr1,arr2),axis=0)

array([[[10, 20, 30]],

       [[15, 25, 35]],

       [[16, 26, 36]],

       [[40, 50, 60]],

       [[45, 55, 65]],

       [[46, 56, 66]]])

In [66]:
np.concatenate((arr1,arr2),axis=1)

array([[[10, 20, 30],
        [40, 50, 60]],

       [[15, 25, 35],
        [45, 55, 65]],

       [[16, 26, 36],
        [46, 56, 66]]])

In [67]:
np.concatenate((arr1,arr2),axis=2)

array([[[10, 20, 30, 40, 50, 60]],

       [[15, 25, 35, 45, 55, 65]],

       [[16, 26, 36, 46, 56, 66]]])

In [68]:
np.concatenate((arr1,arr2))

array([[[10, 20, 30]],

       [[15, 25, 35]],

       [[16, 26, 36]],

       [[40, 50, 60]],

       [[45, 55, 65]],

       [[46, 56, 66]]])

# arr.reshape()-will give a new shape to an array without changing the data

In [69]:
arr3=np.array([10,20,30,40])

In [70]:
arr3.reshape(2,2,)

array([[10, 20],
       [30, 40]])

In [74]:
arr4=np.array([[10,20],[30,40]])
arr4.shape

(2, 2)

In [76]:
#to flatten the array
arr=arr4.reshape(-1)

In [77]:
arr

array([10, 20, 30, 40])

In [78]:
arr.shape

(4,)

# Indexing and slicing

In [79]:
arr3=np.array([10,20,30,40])

In [80]:
arr3[3]

40

In [84]:
#iterate array
for index in range(0,arr3.size):
    print(arr3[index])

10
20
30
40


In [85]:
arr4=np.array([[10,20],[30,40]])

In [90]:
arr4.shape

(2, 2)

In [94]:
for i in range(0,arr4.shape[0]):
    print(arr4[i])

[10 20]
[30 40]


In [105]:
arr3=np.array([10,20,30,40])

In [118]:
#slicing

print(arr3[1:3])
print(arr3[-2:])
print(arr3[-3:])
print(arr3[-4:])
print(arr3[-4:2])
print(arr3[0:3],'==',arr3[-4:-1])

[20 30]
[30 40]
[20 30 40]
[10 20 30 40]
[10 20]
[10 20 30] == [10 20 30]


In [95]:
#slicing
arr4[1:3]

array([[30, 40]])

In [104]:
arr4[-2:]

array([[10, 20],
       [30, 40]])